login:
  path: /login
  defaults: { _controller: AppBundle:Security:login }


event-dispatcher:
  path: /event-dispatcher
  defaults: { _controller: AppBundle:Misc:eventDispatcher }


main:
  path: /
  defaults: { _controller: AppBundle:User:main }

user-hobbies:
  path: /user/hobbies
  defaults: { _controller: AppBundle:User:userHobbies }


users:
  path: /admin/users
  defaults: { _controller: AppBundle:Admin:users }

hobby-users:
  path: /admin/hobby/{hobbyName}
  defaults: { _controller: AppBundle:Admin:displayHobbyUsers }